from flask import Flask, render_template, request, send_file
import pickle
import pdfplumber
import os
import time
from fpdf import FPDF

app = Flask(__name__)

# ---------------- CONFIG ----------------
UPLOAD_FOLDER = "uploads"
app.config["UPLOAD_FOLDER"] = UPLOAD_FOLDER

if not os.path.exists(UPLOAD_FOLDER):
    os.makedirs(UPLOAD_FOLDER)

# ---------------- LOAD MODEL ----------------
model = pickle.load(open("model/model.pkl", "rb"))
cv = pickle.load(open("model/vectorizer.pkl", "rb"))

# ---------------- GLOBAL STORE ----------------
latest_result = None

# ---------------- SKILLS ----------------
skills_list = [
    "java", "python", "sql", "html", "css",
    "javascript", "react", "spring", "mysql",
    "machine learning", "pandas", "flask",
    "power bi", "excel", "api"
]

role_skills = {
    "Backend Developer": ["spring", "mysql", "api", "java"],
    "Frontend Developer": ["html", "css", "javascript", "react"],
    "Data Scientist": ["python", "pandas", "sql", "machine learning"],
    "Software Engineer": ["java", "python", "sql", "api"]
}

# ---------------- HOME ----------------
@app.route('/')
def home():
    return render_template("index.html")


# ---------------- PREDICT ----------------
@app.route('/predict', methods=['POST'])
def predict():

    global latest_result

    file = request.files.get("resume")

    if not file or file.filename == "":
        return render_template("index.html", prediction=None)

    filepath = os.path.join(app.config["UPLOAD_FOLDER"], file.filename)
    file.save(filepath)

    text = ""

    try:
        with pdfplumber.open(filepath) as pdf:
            for page in pdf.pages:
                page_text = page.extract_text()
                if page_text:
                    text += page_text + " "
    except:
        text = ""

    text = text.lower()

    found_skills = [skill for skill in skills_list if skill in text]

    if not found_skills:
        found_skills = ["general"]

    final_text = " ".join(found_skills)
    data = cv.transform([final_text])
    prediction = model.predict(data)[0]

    score = len(found_skills) * 12

    if "project" in text:
        score += 10
    if "internship" in text:
        score += 10
    if "experience" in text:
        score += 10

    score = min(score, 100)

    strength = "Strong" if score >= 80 else "Average" if score >= 50 else "Weak"

    expected = role_skills.get(prediction, [])
    missing = [skill for skill in expected if skill not in found_skills]

    skills_text = ", ".join(found_skills)
    missing_text = ", ".join(missing) if missing else "No Missing Skills"

    # SAVE RESULT
    latest_result = {
        "prediction": prediction,
        "score": score,
        "skills": skills_text,
        "missing": missing_text,
        "strength": strength
    }

    return render_template(
        "index.html",
        prediction=prediction,
        score=score,
        skills=skills_text,
        strength=strength,
        missing=missing_text
    )


# ---------------- DOWNLOAD PDF ----------------
@app.route('/download')
def download():

    global latest_result

    if not latest_result:
        return render_template("index.html", prediction=None)

    filename = f"report_{int(time.time())}.pdf"

    pdf = FPDF()
    pdf.add_page()

    pdf.set_font("Arial", "B", 16)
    pdf.cell(200, 10, txt="AI Resume Analyzer Report", ln=True, align='C')

    pdf.ln(10)

    pdf.set_font("Arial", size=12)

    pdf.cell(200, 10, txt=f"Predicted Role: {latest_result['prediction']}", ln=True)
    pdf.cell(200, 10, txt=f"ATS Score: {latest_result['score']}/100", ln=True)
    pdf.cell(200, 10, txt=f"Resume Strength: {latest_result['strength']}", ln=True)
    pdf.cell(200, 10, txt=f"Skills Found: {latest_result['skills']}", ln=True)
    pdf.cell(200, 10, txt=f"Missing Skills: {latest_result['missing']}", ln=True)

    pdf.ln(10)
    pdf.cell(200, 10, txt="Generated by AI Resume Analyzer Pro", ln=True)

    pdf.output(filename)

    return send_file(filename, as_attachment=True)


# ---------------- RUN ----------------
if __name__ == "__main__":
    app.run(debug=True)